language: cpp
cache:
  - pip
  - ccache

dist: focal
group: edge

addons:
  apt:
    sources:
      - sourceline: 'deb http://apt.llvm.org/focal/ llvm-toolchain-focal-12 main'
        key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
    packages:
      - ninja-build
      - parallel
      - g++-10
      - clang-format-12

os:
  - linux

before_script:
  - ccache --zero-stats

after_script:
  - ccache --show-stats

install:
  - pip install --user cmakelang

script:
  - CLANG_FORMAT=clang-format-12 hack/fmt chk
  - CC=gcc-10 CXX=g++-10 LDFLAGS=-fuse-ld=lld hack/hack gen Debug build
  - hack/hack test build

