#!/usr/bin/env bash

set -e -u -o pipefail

: "${CLANG_FORMAT:=clang-format}"

# NUL-delimited list of files to format
files_to_format() {
	git ls-files -z ':!/vendor' '*.cc' '*.h'
}

fmt() {
	cmake-format --in-place CMakeLists.txt
	files_to_format | parallel -P +0 -0 \
		"${CLANG_FORMAT}" -i
}

chk() {
	cmake-format --check CMakeLists.txt
	# --halt: fail as soon as we encounter the first formatting diagnostic
	files_to_format | parallel -q -0 \
		--halt now,fail=1 \
		"${CLANG_FORMAT}" -dry-run -ferror-limit 1 -Werror
}

usage() {
	printf >&2 "Usage: [CLANG_FORMAT=clang-format] %s (fmt|chk)\n" "$0"

	return 1
}

_main() {
	local cmd
	cmd=${1:-}
	case "${cmd}" in
	fmt)
		fmt
		;;
	chk)
		chk
		;;
	*)
		usage
		;;
	esac
}

_main "$@"
